remote_theme: daattali/beautiful-jekyll@6.0.1
plugins:
  - jekyll-include-cache
  
layout: single
classes: wide

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
