plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "dark"

title: "OC Directory"
description: "A Hub for original characters and worldbuilding."
layout: "single"
search: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "single"
