remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "dark"
plugins:
  - jekyll-include-cache

head_scripts:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css

footer_scripts:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js

sass:
  # loading path from site root
  # default to _sass
  sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed
  
layout: splash
classes: wide

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      classes: wide
      author_profile: false
