remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "dark"
plugins:
  - jekyll-include-cache
  
layout: single
classes: wide

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
