title: "OC Directory"
description: "A hub for my original characters and worldbuilding."

header_pages:
  - lore.md

plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
