remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dark"
plugins:
  - jekyll-include-cache
  
layout: single

defaults:
  - scope:
      path: ""
      layout: single
