remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: "Compendium"
title_separator: "-"

plugins:
  - jekyll-include-cache

atom_feed:
  hide: true

collections:
  portfolio:
    output: true
    permalink: ""

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      author_profile: false
      share: false

defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: false



