remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

title: "Compendium"
title_separator: "-"

plugins:
  - jekyll-include-cache

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      author_profile: false
      share: false

head_scripts:
  - https://unpkg.com/lucide-static@latest/icons/home.svg
  - https://unpkg.com/lucide@latest/dist/umd/lucide.js
  - https://unpkg.com/lucide@latest

