theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "dark"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

layout: single

defaults:
  - scope:
      path: ""
      layout: single
