remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin    : "dark"
plugins:
  - jekyll-include-cache

head_scripts:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css

footer_scripts:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js
  
layout: splash
classes: wide

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      classes: wide
      author_profile: false
