theme: just-the-docs
plugins:
  - jekyll-include-cache
  
layout: splash
classes: wide

defaults:
  # _posts
  - scope:
      path: ""
      type: pages
    values:
      layout: splash
      classes: wide
      author_profile: false
